### ISSUE TITLE
Download size specification? 

### ISSUE THREAD

**Issue by jgearhart** [Daniel-KM/Omeka-S-module-Mirador#5]
Hi, 
I have high resolution images but permission restrictions require no more than 1024px on the longest side should be available for downloading. 
Is this possible? If it is can you tell me where in the code to achieve this? 
Thank you!

**Comment by Daniel-KM** [comment]
The issue is the download link or the image displayed in the viewer? 
Anyway, first, if the user sees the image, it is already downloaded in his computer. The fact that there is a download link or not is only a facility. Second, If the image is tiled, small scripts exist that can rebuild the initial image. 
The easiest to avoid to display the link is to change the css of it. I think there is an option somewhere in Mirador config for that, but you can ask to the Mirador people for that.

**Comment by jgearhart** [comment]
Thanks for the help (I think I was actually referring to UV and posted that in this thread for Mirador by mistake). I have media-specific metadata that is not showing up in the information panel in Mirador. It shows up fine in UV (i defined the fields in the iiif module configuration) but I would prefer Mirador. In other words, I have items with multiple images (media) with specific information I want seen (and not seen) in the mirador information panel.

**Comment by Daniel-KM** [comment]
There is a mirador plugin for that in  the site config : mirador metadata.

**Comment by jgearhart** [comment]
I see. Thank you. 
Any idea why I still might not be getting good zoomed details from a 100MB TIF uploaded via Tiler?

**Comment by Daniel-KM** [comment]
Did the tilling finish?

**Comment by Daniel-KM** [comment]
Issue related to ImageServer.
